-- V2: forum threads and comments (discussion thread per file)
-- thread_comments.parent_comment_id cascade: deleting a comment removes its whole
-- reply subtree at the database level (service layer also removes it explicitly).

create table forum_threads (
    id bigint generated by default as identity primary key,
    file_id bigint not null unique references files (id) on delete cascade,
    locked boolean not null default false,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

create table thread_comments (
    id bigint generated by default as identity primary key,
    thread_id bigint not null references forum_threads (id) on delete cascade,
    author_id bigint not null references users (id),
    content varchar(2000) not null,
    parent_comment_id bigint references thread_comments (id) on delete cascade,
    referenced_file_id bigint references files (id) on delete set null,
    created_at timestamp(6) with time zone,
    edited_at timestamp(6) with time zone
);